os: Visual Studio 2015
version: "{build}"
build: off
platform: x64
environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4
install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm i -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --build-from-source
matrix:
  fast_finish: true
shallow_clone: true
clone_depth: 1
test_script: npm t
